name: Translator CI/CD

on:
  push:
    branches: [ "main", "dataformat-changes" ]
  pull_request:
    branches: [ "main", "dataformat-changes" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: mvn -B package --file ./Translator/pom.xml
    - name: Test
      run: mvn test --file ./Translator/pom.xml
